Hw 10
blestem/CURSOR_Martian-Manhunter_HW- pull request #7
Opened 2021-06-06 20:57 UTC by blestem

2021-07-09 19:20 UTC, dimigor requested changes

2021-07-09 19:20 UTC, dimigor commented on hw_10/app.py
> +        return render_template('calc.html', func="Null")
щоб не писати купу цих ретурнів, зроби мапу з назвами функцій, на яку віддавай символ операції
а потім для результату використовуй функцію eval()

2021-07-20 19:14 UTC, dimigor approved these changes

2021-07-21 08:53 UTC, blestem commented
done

2021-07-21 09:09 UTC, closed without merging